import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
           <header style={{ background: "black", color: "white", padding: "10px" }}>
          <h2>My Website</h2>
        </header>
        <Navbar />
        <main>
          {children}
        </main>

        <footer style={{ background: "gray", padding: "10px" }}>
          <p>© 2026 My App</p>
        </footer>
      </body>
    </html>
  );
}
